version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: begraceful
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  auth_service:
    build: ./auth_service
    environment:
      DATABASE_URL: "postgres://pguser:pgpass@db:5432/begraceful?sslmode=disable"
      JWT_SECRET: "super-secret-key"
      PROFILE_SERVICE_URL: "http://profile_service:8080"
    depends_on:
      - db
    ports:
      - "8001:8080"

  profile_service:
    build: ./profile_service
    environment:
      DATABASE_URL: "postgres://pguser:pgpass@db:5432/begraceful?sslmode=disable"
    depends_on:
      - db
    ports:
      - "8002:8080"

volumes:
  db-data:
